services:
  nginx:
    image: nginx:1.22-alpine
    container_name: maildrop-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    depends_on:
      - api
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email you@example.com
      --agree-tos --no-eff-email
      --key-type ecdsa --elliptic-curve secp384r1
      -d api2.freecustom.email
      -d mail.freecustom.email
  
  certbot-renew:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: sh -c "certbot renew --quiet && nginx -s reload && pkill -HUP haraka"
    depends_on:
      - nginx
      - haraka
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: maildrop-api
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/freecustomemail?authSource=admin
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3000"
    restart: unless-stopped

  haraka:
    build:
      context: ./smtp-fast
    container_name: maildrop-smtp
    ports:
      - "25:25"
      - "587:587"
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/freecustomemail?authSource=admin
    volumes:
      - certs:/etc/letsencrypt:ro
      - ./smtp-fast/src/config:/smtp-fast/src/config
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_server
    command: [ "redis-server", "--bind", "0.0.0.0", "--appendonly", "yes" ]
    restart: unless-stopped
    volumes:
      - maildrop_redis_data:/data

  mongo:
    image: mongo:7
    container_name: mongo_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: freecustomemail
    restart: unless-stopped
    volumes:
      - maildrop_mongo_data:/data/db

volumes:
  maildrop_mongo_data:
  maildrop_redis_data:
  certs:
