version: "3.9"

services:
  haraka:
    build:
      context: ./smtp-fast
    container_name: maildrop-smtp
    network_mode: host
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      MONGO_URI: mongodb://127.0.0.1:27017/freecustomemail
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: maildrop-api
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis://redis:6379
      MONGO_URI: mongodb://mongo:27017/freecustomemail
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    command: [ "redis-server", "--bind", "0.0.0.0" ]
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo_server
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
