# in config/tls.ini
key=tls_key.pem
cert=tls_cert.pem

minVersion=TLSv1.3
honorCipherOrder=true
ciphers=TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384
ecdhCurve=prime256v1
requestCert=false
rejectUnauthorized=false

# Disable OCSP for maximum connection speed
requestOCSP=false