[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid # Use /tmp for non-root user

[program:haraka]
# Use the npm-installed haraka executable
command=node_modules/.bin/haraka -c src
process_name=haraka
directory=/maildrop
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
exitcodes=0,2
stopsignal=TERM
stopwaitsecs=10
user=smtp # Tell supervisor to run haraka as the smtp user

[eventlistener:processes]
command=./stop-supervisor.sh
events=PROCESS_STATE_FATAL