# Path relative to Haraka's config directory
key=tls_key.pem
cert=tls_cert.pem


# Only allow modern TLS
minVersion=TLSv1.3
honorCipherOrder=true

# Fast + secure TLS 1.3 ciphers
ciphers=TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384

# Use optimized ECDH curve
ecdhCurve=prime256v1

# Disable client cert auth (not used in SMTP)
requestCert=false
rejectUnauthorized=false

# Enable OCSP stapling if using public certs (optional)
requestOCSP=true
